[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

# goconvey breaks without this
# 1.6.0 was too old
[[override]]
  name = "github.com/smartystreets/assertions"
  branch = "master"
